package interfaces1;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author davidvazquezcervantes
 */
public class catalogo extends javax.swing.JFrame {
            DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form catalogo
     */
    public catalogo() {   
        initComponents();
                this.setLocationRelativeTo(null);

        try {
            tabla.setModel(modelo);
            PreparedStatement ps = null;
            ResultSet rs = null;
            Ganaderia conn = new Ganaderia();
            java.sql.Connection con = Ganaderia.getConection();

            String sql = "Select id_ganaderos, nombre, ap_pat, ap_mat, edad, genero, no_tel, nom_gan, n_calle, numero, colonia, ciudad, cp, fecha, no_litros, no_acciones FROM ganaderos";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

                  modelo.addColumn("ID");
             modelo.addColumn("Nombre");
            modelo.addColumn("Apellido paterno");
            modelo.addColumn("Apellido materno");
            modelo.addColumn("Edad");
            modelo.addColumn("genero");
            modelo.addColumn("Numero Telefono");
            modelo.addColumn("Nombre ganaderia");
            modelo.addColumn("Direccion");
            modelo.addColumn("Numero");
            modelo.addColumn("colonia");
            modelo.addColumn("ciudad");
            modelo.addColumn("cp");
            modelo.addColumn("fecha");
            modelo.addColumn("nolitros");
           // modelo.addColumn("");             int[] ancho=(100,100,100,100,100,100,100,100,100,100,100,100,100,100,100);

            modelo.addColumn("noacciones");


            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "¡Error al eliminar registro!!"+ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ap_mat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ap_pat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        no_tel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        fecha = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nom_gan = new javax.swing.JTextField();
        n_calle = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        ciudad = new javax.swing.JTextField();
        colonia = new javax.swing.JTextField();
        cp = new javax.swing.JTextField();
        jlabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        no_acciones = new javax.swing.JTextField();
        no_litros = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 640));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(196, 149, 95));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel de Acciones"));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/90GUARDAR.png"))); // NOI18N
        jButton1.setText("GUARDAR");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/90GUARDAR.png"))); // NOI18N
        jButton1.setRolloverEnabled(true);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/45GUARDAR.png"))); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/90ELIMINAR.png"))); // NOI18N
        jButton3.setText("ELIMINAR");
        jButton3.setContentAreaFilled(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/90ELIMINAR.png"))); // NOI18N
        jButton3.setRolloverEnabled(true);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/45ELIMINAR.png"))); // NOI18N
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/HOME.png"))); // NOI18N
        jButton5.setText("MENU PRINCIPAL");
        jButton5.setContentAreaFilled(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/HOME.png"))); // NOI18N
        jButton5.setRolloverEnabled(true);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/HOME50.png"))); // NOI18N
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel18.setText("Buscar Por Nombre");

        buscar.setBackground(new java.awt.Color(255, 153, 102));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/90BUSCAR.png"))); // NOI18N
        jButton4.setText("BUSCAR Y/O MOSTRAR TODO");
        jButton4.setContentAreaFilled(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/90BUSCAR.png"))); // NOI18N
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/45BUSCAR.png"))); // NOI18N
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/90MODIFICAR.png"))); // NOI18N
        jButton2.setText("Actualizar");
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/90MODIFICAR.png"))); // NOI18N
        jButton2.setRolloverEnabled(true);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/45MODIFICAR.png"))); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1170, 170));

        jPanel4.setBackground(new java.awt.Color(196, 149, 95));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del ganadero"));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setText("Nombre");

        nombre.setBackground(new java.awt.Color(255, 153, 102));
        nombre.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 0)));
        nombre.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel4.setText("Edad");

        edad.setBackground(new java.awt.Color(255, 153, 102));
        edad.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(255, 204, 51)));
        edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadActionPerformed(evt);
            }
        });
        edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edadKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel3.setText("Apellido materno");

        ap_mat.setBackground(new java.awt.Color(255, 153, 102));
        ap_mat.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(255, 204, 51)));
        ap_mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap_matActionPerformed(evt);
            }
        });
        ap_mat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ap_matKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel2.setText("Apellido paterno");

        ap_pat.setBackground(new java.awt.Color(255, 153, 102));
        ap_pat.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 51), new java.awt.Color(0, 0, 0)));
        ap_pat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap_patActionPerformed(evt);
            }
        });
        ap_pat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ap_patKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel6.setText("Número de télefono");

        no_tel.setBackground(new java.awt.Color(255, 153, 102));
        no_tel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 51), new java.awt.Color(0, 0, 0)));
        no_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_telActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel5.setText("Género");

        jPanel5.setBackground(new java.awt.Color(196, 149, 95));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        jLabel13.setText("AÑO-MES-DIA");

        jLabel14.setText("0000-00-00");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel15.setText("Formato de ingreso");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel14))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(9, 9, 9)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jPanel2.setBackground(new java.awt.Color(196, 149, 95));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la ganadería"));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel7.setText("Nombre de la ganadería");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel8.setText("Nombre de la calle");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel9.setText("Número");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel11.setText("Ciudad");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel10.setText("Colonia");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel12.setText("Código Postal");

        nom_gan.setBackground(new java.awt.Color(255, 153, 102));
        nom_gan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nom_ganKeyTyped(evt);
            }
        });

        n_calle.setBackground(new java.awt.Color(255, 153, 102));
        n_calle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                n_calleKeyTyped(evt);
            }
        });

        numero.setBackground(new java.awt.Color(255, 153, 102));
        numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroKeyTyped(evt);
            }
        });

        ciudad.setBackground(new java.awt.Color(255, 153, 102));
        ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadActionPerformed(evt);
            }
        });
        ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ciudadKeyTyped(evt);
            }
        });

        colonia.setBackground(new java.awt.Color(255, 153, 102));
        colonia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                coloniaKeyTyped(evt);
            }
        });

        cp.setBackground(new java.awt.Color(255, 153, 102));
        cp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cpKeyTyped(evt);
            }
        });

        jlabel23.setFont(new java.awt.Font("Raanana", 3, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nom_gan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colonia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(n_calle, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabel23)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nom_gan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(n_calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jlabel23))
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        jPanel1.setBackground(new java.awt.Color(196, 149, 95));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel17.setText("Número de Acciones");

        no_acciones.setBackground(new java.awt.Color(255, 153, 102));
        no_acciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_accionesActionPerformed(evt);
            }
        });
        no_acciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                no_accionesKeyTyped(evt);
            }
        });

        no_litros.setBackground(new java.awt.Color(255, 153, 102));
        no_litros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_litrosActionPerformed(evt);
            }
        });
        no_litros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                no_litrosKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel16.setText("Número de litros aportados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(no_litros, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(no_acciones, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(no_litros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(no_acciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ap_mat, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(no_tel, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(ap_pat, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(ap_pat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ap_mat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(no_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))))))))
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 1170, 600));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iu-14.jpg"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();

        menucatalogo p1= new menucatalogo();
        p1.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PreparedStatement ps = null;

        try{
            Ganaderia objCon = new Ganaderia();
            Connection conn = Ganaderia.getConection();
            int Fila = tabla.getSelectedRow();
            String codigo = tabla.getValueAt(Fila, 1).toString();
            ps = conn.prepareStatement("DELETE FROM ganaderos WHERE nombre=?");
            ps.setString(1, codigo);
            ps.execute();

            modelo.removeRow(Fila);
            
            JOptionPane.showMessageDialog(null, "¡Listo! Registro Eliminado");

            nombre.setText("");
            ap_pat.setText("");
            ap_mat.setText("");
            edad.setText("");
            jComboBox1.setSelectedIndex(0);
            no_tel.setText("");
            nom_gan.setText("");
            n_calle.setText("");
            numero.setText("");
            colonia.setText("");
            ciudad.setText("");
            cp.setText("");
            fecha.setText("");
            no_litros.setText("");
            no_acciones.setText("");
            buscar.setText("");
        
        
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error al Eliminar Producto"+ex);
            System.out.println(ex.toString());

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
              try{
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost/bd_ganaderos","root","");
            PreparedStatement pst = cn.prepareStatement("insert into ganaderos value(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1,"0");
            pst.setString(2, nombre.getText().trim());
            pst.setString(3, ap_pat.getText().trim());
            pst.setString(4, ap_mat.getText().trim());
            pst.setString(5, edad.getText().trim());
            pst.setString(6, jComboBox1.getSelectedItem().toString());
            pst.setString(7, no_tel.getText().trim());
            pst.setString(8, nom_gan.getText().trim());
            pst.setString(9, n_calle.getText().trim());
            pst.setString(10, numero.getText().trim());
            pst.setString(11, colonia.getText().trim());
            pst.setString(12, ciudad.getText().trim());
            pst.setString(13, cp.getText().trim());
            pst.setDate(14, Date.valueOf(fecha.getText().trim()));
            pst.setString(15, no_litros.getText().trim());
            pst.setString(16, no_acciones.getText().trim());

            pst.executeUpdate();
                        JOptionPane.showMessageDialog(null, "REGISTRO EXITOSO,"
                    + "");

            Object[] fila = new Object[16];
//                        fila[1] = nombre.getText();

            fila[1] = nombre.getText();
            fila[2] = ap_pat.getText();
            fila[3] = ap_mat.getText();
            fila[4] = edad.getText();
            fila[5] = jComboBox1.getSelectedItem().toString();
            fila[6] = no_tel.getText();
            fila[7] = nom_gan.getText();
            fila[8] = n_calle.getText();
            fila[9] = numero.getText();
            fila[10] = colonia.getText();
            fila[11] = ciudad.getText();
            fila[12] = cp.getText();
            fila[13] = Date.valueOf(fecha.getText());
            fila[14] = no_litros.getText();
            fila[15] = no_acciones.getText();

            modelo.addRow(fila);

            nombre.setText("");
            ap_pat.setText("");
            ap_mat.setText("");
            edad.setText("");
            no_tel.setText("");
            nom_gan.setText("");
            n_calle.setText("");
            numero.setText("");
            colonia.setText("");
            ciudad.setText("");
            cp.setText("");
            no_litros.setText("");
            no_acciones.setText("");


        }catch(Exception e){
            System.out.println(""+e);
            JOptionPane.showMessageDialog(null, "REVISE LOS DATOS");
        }



    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String camp=buscar.getText();
            String where="";
                if(!"".equals(camp))
                            {
                                   where="WHERE nombre='" + camp + "'";
                            }

        try{
            DefaultTableModel modelo = new DefaultTableModel();
            tabla.setModel(modelo);

            PreparedStatement ps=null;
            ResultSet rs=null;           
            Ganaderia conn= new Ganaderia();
            Connection con=Ganaderia.getConection();
            String sql = "Select id_ganaderos, nombre, ap_pat, ap_mat, edad, genero, no_tel, nom_gan, n_calle, numero, colonia, ciudad, cp, fecha, no_litros, no_acciones FROM ganaderos " + where;
            System.out.println(""+sql);
            ps=con.prepareStatement(sql);            
            rs=ps.executeQuery();
            
            ResultSetMetaData rsmd=rs.getMetaData();
            int ccolumnas=rsmd.getColumnCount();
            modelo.addColumn("ID");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido paterno");
            modelo.addColumn("Apellido materno");
            modelo.addColumn("Edad");
            modelo.addColumn("genero");
            modelo.addColumn("Numero Telefono");
            modelo.addColumn("Nombre ganaderia");
            modelo.addColumn("Direccion");
            modelo.addColumn("Numero");
            modelo.addColumn("colonia");
            modelo.addColumn("ciudad");
            modelo.addColumn("cp");
            modelo.addColumn("fecha");
            modelo.addColumn("nolitros");
           // modelo.addColumn("");             int[] ancho=(100,100,100,100,100,100,100,100,100,100,100,100,100,100,100);

            modelo.addColumn("noacciones");

            
            while(rs.next()){
                Object[] filas = new Object[ccolumnas];
                for(int i=0;i<ccolumnas;i++){
                    filas[i]=rs.getObject(i+1);
                }
                modelo.addRow(filas);
            }
            
        } catch (SQLException ex) {
             System.err.println(ex.toString());
                                     JOptionPane.showMessageDialog(null, "¡Error al hacer el evento !!  "+ex);

         }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
 char c=evt.getKeyChar();
 if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' ')) evt.consume();

    }//GEN-LAST:event_nombreKeyTyped

    private void ap_patKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ap_patKeyTyped
char c=evt.getKeyChar();

 if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' ')) evt.consume();    }//GEN-LAST:event_ap_patKeyTyped

    private void ap_matKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ap_matKeyTyped
char c=evt.getKeyChar();
 if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' ')) evt.consume();    }//GEN-LAST:event_ap_matKeyTyped

    private void nom_ganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nom_ganKeyTyped
char c=evt.getKeyChar();
 if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' ')) evt.consume();    }//GEN-LAST:event_nom_ganKeyTyped

    private void n_calleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n_calleKeyTyped
char c=evt.getKeyChar();
 if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' ')) evt.consume();    }//GEN-LAST:event_n_calleKeyTyped

    private void ciudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ciudadKeyTyped
char c=evt.getKeyChar();
 if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' ')) evt.consume();    }//GEN-LAST:event_ciudadKeyTyped

    private void coloniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coloniaKeyTyped
char c=evt.getKeyChar();
 if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' ')) evt.consume();    }//GEN-LAST:event_coloniaKeyTyped

    private void edadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edadKeyTyped
char c=evt.getKeyChar();
 if((c<'0'||c>'9')) evt.consume();    }//GEN-LAST:event_edadKeyTyped

    private void numeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroKeyTyped

char c=evt.getKeyChar();
 if((c<'0'||c>'9')) evt.consume();    }  
        private void cpKeyTyped(java.awt.event.KeyEvent evt) {   
            

char c=evt.getKeyChar();
 if((c<'0'||c>'9')) evt.consume();
    }//GEN-LAST:event_numeroKeyTyped

        
    /*
        
    private void cpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpKeyTyped
    }//GEN-LAST:event_cpKeyTyped
*/
    private void no_litrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_litrosKeyTyped

char c=evt.getKeyChar();
 if((c<'0'||c>'9')) evt.consume();

    }//GEN-LAST:event_no_litrosKeyTyped

    private void no_accionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_accionesKeyTyped
        char c=evt.getKeyChar();
 if((c<'0'||c>'9')) evt.consume();

    }//GEN-LAST:event_no_accionesKeyTyped

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    private void ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadActionPerformed

    private void ap_patActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap_patActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap_patActionPerformed

    private void ap_matActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap_matActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap_matActionPerformed

    private void no_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_telActionPerformed

    private void edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadActionPerformed

    private void no_litrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_litrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_litrosActionPerformed

    private void no_accionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_accionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_accionesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            int Fila = tabla.getSelectedRow();
            tabla.setModel(modelo);

        PreparedStatement ps = null;
   
        
        try {
        Ganaderia objCon = new Ganaderia();
            Connection conn = Ganaderia.getConection();
            ps = conn.prepareStatement("UPDATE ganaderos SET nombre=?, ap_pat=?,ap_mat=?,edad=?,genero=?,"
                    + "no_tel=?,nom_gan=?,n_calle=?,numero=?,colonia=?,ciudad=?,"
                    + "cp=?,fecha=?,no_litros=?,no_acciones=? WHERE nombre=?");
        ps.setString(1,"1");
            ps.setString(2, nombre.getText());
            ps.setString(3, ap_pat.getText());
            ps.setString(4, ap_mat.getText());
            ps.setString(5, edad.getText());
            ps.setString(6, jComboBox1.getSelectedItem().toString());
            ps.setString(7, no_tel.getText().trim());
            ps.setString(8, nom_gan.getText().trim());
            ps.setString(9, n_calle.getText().trim());
            ps.setString(10, numero.getText().trim());
            ps.setString(11, colonia.getText().trim());
            ps.setString(12, ciudad.getText().trim());
            ps.setString(13, cp.getText().trim());
            ps.setDate(14, Date.valueOf(fecha.getText().trim()));
            ps.setString(15, no_litros.getText().trim());
            ps.setString(16, no_acciones.getText().trim());

            /*
            pst.setString(1,"0");
            pst.setString(2, nombre.getText().trim());
            pst.setString(3, ap_pat.getText().trim());
            pst.setString(4, ap_mat.getText().trim());
            pst.setString(5, edad.getText().trim());
            pst.setString(6,jComboBox1.getSelectedItem().toString());
            pst.setString(7, no_tel.getText().trim());
            pst.setString(8, nom_gan.getText().trim());
            pst.setString(9, n_calle.getText().trim());
            pst.setString(10, numero.getText().trim());
            pst.setString(11, colonia.getText().trim());
            pst.setString(12, ciudad.getText().trim());
            pst.setString(13, cp.getText().trim());
            pst.setDate(14, Date.valueOf(fecha.getText().trim()));
            pst.setString(15, no_litros.getText().trim());
            pst.setString(16, no_acciones.getText().trim());
            */

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Datos Modificados");
            tabla.setValueAt(nombre.getText(), Fila, 1);
            tabla.setValueAt(ap_pat.getText(), Fila, 2);
            tabla.setValueAt(ap_mat.getText(), Fila, 3);
            tabla.setValueAt(edad.getText(), Fila, 4);
            tabla.setValueAt(jComboBox1.getSelectedItem().toString(), Fila, 5);
            tabla.setValueAt(no_tel.getText(), Fila, 6);
            tabla.setValueAt(nom_gan.getText(), Fila, 7);
            tabla.setValueAt(n_calle.getText(), Fila, 8);
            tabla.setValueAt(numero.getText(), Fila, 9);
            tabla.setValueAt(colonia.getText(), Fila, 10);
            tabla.setValueAt(ciudad.getText(), Fila, 11);
            tabla.setValueAt(cp.getText(), Fila, 12);
            tabla.setValueAt(Date.valueOf(fecha.getText().trim()), Fila, 13);
            tabla.setValueAt(no_litros.getText(), Fila, 14);
            tabla.setValueAt(no_acciones.getText(), Fila, 15);



}catch(SQLException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "¡Error al actualizar registrp!! "+e);


}  



    }//GEN-LAST:event_jButton2ActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
PreparedStatement ps = null;
        ResultSet rs = null;
        try{
            Ganaderia objCon = new Ganaderia();
            Connection conn = Ganaderia.getConection();
            int Fila = tabla.getSelectedRow();
            String id = tabla.getValueAt(Fila, 1).toString();
            ps = conn.prepareStatement("Select nombre, ap_pat, ap_mat, edad,"
                    + " genero, no_tel, nom_gan, n_calle,"
                    + " numero, colonia, ciudad, cp, fecha, "
                    + "no_litros, no_acciones FROM ganaderos where nombre=? ");
            ps.setString(1, id);
            rs = ps.executeQuery();
            while (rs.next()) {
                nombre.setText(rs.getString("nombre"));
                ap_pat.setText(rs.getString("ap_pat"));
                ap_mat.setText(rs.getString("ap_mat"));
                edad.setText(rs.getString("edad"));
            jComboBox1.setSelectedIndex(0);
                no_tel.setText(rs.getString("no_tel"));
                nom_gan.setText(rs.getString("nom_gan"));
                n_calle.setText(rs.getString("n_calle"));
                numero.setText(rs.getString("numero"));
                colonia.setText(rs.getString("colonia"));
                ciudad.setText(rs.getString("ciudad"));
                cp.setText(rs.getString("cp"));
                fecha.setText(rs.getString("fecha"));
                no_litros.setText(rs.getString("no_litros"));
                no_acciones.setText(rs.getString("no_acciones"));

            }

        }catch(SQLException ex){
                        System.out.println(ex.toString());
                        JOptionPane.showMessageDialog(null, "¡Error al hacer el evento !! "+ex);

        }    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ap_mat;
    private javax.swing.JTextField ap_pat;
    private javax.swing.JTextField buscar;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField colonia;
    private javax.swing.JTextField cp;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabel23;
    private javax.swing.JTextField n_calle;
    private javax.swing.JTextField no_acciones;
    private javax.swing.JTextField no_litros;
    private javax.swing.JTextField no_tel;
    private javax.swing.JTextField nom_gan;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numero;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
